version: "3.8"

services:
  nginx-proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-web:/var/www/certbot
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-web:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email email@example.com --agree-tos --no-eff-email -d <domain>

volumes:
  certbot-etc:
  certbot-var:
  certbot-web:

networks:
  proxy-network:
    driver: bridge
