services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - "3080:80"
    environment:
      - DRONE_GITEA_SERVER=http://forgejo:3000
      - DRONE_GITEA_CLIENT_ID=<from Forgejo>
      - DRONE_GITEA_CLIENT_SECRET=<from Forgejo>
      - DRONE_RPC_SECRET=super-secret
      - DRONE_SERVER_HOST=drone:3080
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:your_admin_user,admin:true
    volumes:
      - ./drone:/data
