services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - "80:80"
    environment:
      - DRONE_GITEA_SERVER=http://forgejo:3000
      - DRONE_GITEA_CLIENT_ID=<from Forgejo>
      - DRONE_GITEA_CLIENT_SECRET=<from Forgejo>
      - DRONE_RPC_SECRET=super-secret
      - DRONE_SERVER_HOST=drone:80
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:your_admin_user,admin:true
      - DRONE_DATABASE_DRIVER=postgres
      - DRONE_DATABASE_DATASOURCE=postgres://drone:dronepass@drone-postgres:5432/drone?sslmode=disable
    volumes:
      - ./drone:/data
    restart: unless-stopped
