version: "3.8"

services:
  restic-backup:
    image: restic/restic:latest
    container_name: restic-backup
    environment:
      - RESTIC_REPOSITORY=s3:s3.amazonaws.com/backup-restic
      - AWS_ACCESS_KEY_ID=AKIA2222222222222222
      - AWS_SECRET_ACCESS_KEY=1234567890
      - RESTIC_PASSWORD=1234567890
      - TZ=Europe/Kyiv
    volumes:
      - /your/local/data:/data:ro
      - /your/local/restic-cache:/root/.cache/restic
    entrypoint: /bin/sh
    command: >
      -c "
      restic init || true &&
      restic backup /data &&
      restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --prune
      "
